/**
 * Codex app-server JSON-RPC client — the transport half of the codex-direct
 * engine.
 *
 * TRANSPORT DECISION (2026-08-14): the installed `codex` BINARY's app-server
 * protocol, not an SDK package. `package.json` has no codex SDK, and adding
 * one would be a second, differently-versioned way to talk to a binary this
 * deployment already requires:
 *  - codex-usage.ts already speaks this exact protocol in production
 *    (`codex app-server` + newline-delimited JSON-RPC + the
 *    initialize/initialized handshake), and codex-usage.test.ts already proves
 *    a fake binary is a working test seam. This module is that pattern
 *    generalized from one request to a full duplex session.
 *  - The v2 protocol is a superset of what any thin SDK wrapper exposes and
 *    covers every point of the engine contract: `thread/start` /
 *    `thread/resume` (the thread id we journal as codexThreadId),
 *    `turn/start`, `turn/steer` (REAL mid-turn injection, so steer() can
 *    return true), `turn/interrupt` (quiet cancel), streaming `item/*`
 *    notifications, `thread/tokenUsage/updated` for TurnUsage, and
 *    `turn/completed` carrying a typed `codexErrorInfo` — including
 *    `usageLimitExceeded`, which is a first-class signal rather than a string
 *    match.
 *  - The schemas this client is written against are generated by the binary
 *    itself (`codex app-server generate-json-schema --out <dir>`), so a codex
 *    upgrade can be re-checked without guesswork. Pinned observation:
 *    codex-cli 0.144.5.
 *
 * The client is deliberately dumb: framing, request/response correlation,
 * server→client request dispatch, and process lifetime. Every policy decision
 * (auth, sandbox, MCP, approvals) lives in codex-direct-adapter.ts.
 */

/** The codex binary. Read at call time so the env override works as a test
 *  seam regardless of module-import order; it is a test/ops seam, not a
 *  feature switch. */
export function codexBinary(): string {
  return process.env.OPENSESSION_CODEX_BIN || "codex";
}

/** Wall cap on a single JSON-RPC call. Turn progress arrives as
 *  NOTIFICATIONS, so no in-turn request legitimately runs long; the turn
 *  itself is bounded by the caller's cancel path, not by this. */
const DEFAULT_REQUEST_TIMEOUT_MS = 60_000;

/** Guard against an unbounded stdout line (a wedged/hostile child). */
const MAX_BUFFER_BYTES = 8_000_000;

export interface CodexRpcHandlers {
  /** Server→client notification (no id): `item/completed`, `turn/completed`, … */
  onNotification(method: string, params: any): void;
  /** Server→client REQUEST (has an id): approvals, user-input asks. Resolve
   *  with the result payload; a throw is answered as a JSON-RPC error. */
  onRequest(method: string, params: any): Promise<unknown>;
  /** Raw stderr text, for diagnostics only. */
  onStderr?(text: string): void;
  /** Process exit. `code` is null when the process was signalled. */
  onExit?(code: number | null): void;
}

export interface CodexAppServerSpawnOptions {
  /** Minimal, explicit env — the caller builds it; nothing is inherited here. */
  env: Record<string, string>;
  executable?: string;
  cwd?: string;
  /** `-c key=value` config overrides, already TOML-encoded (codexConfigArgs). */
  configArgs?: string[];
  handlers: CodexRpcHandlers;
}

/** TOML-encode one config value for a `-c key=value` override. Codex parses
 *  the value as TOML and falls back to a literal string, so quoting matters:
 *  an unquoted path with a `/` is fine as a literal, but an unquoted `{`
 *  would parse as a broken inline table. */
export function tomlValue(value: unknown): string {
  if (value === null || value === undefined) return '""';
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(tomlValue).join(", ")}]`;
  const entries = Object.entries(value as Record<string, unknown>).filter(
    ([, v]) => v !== undefined
  );
  return `{ ${entries.map(([k, v]) => `${tomlKey(k)} = ${tomlValue(v)}`).join(", ")} }`;
}

/** Bare keys where codex's TOML allows them, quoted otherwise (server names
 *  and cwd paths routinely contain dots and slashes). */
export function tomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : JSON.stringify(key);
}

/** `{ "model": "gpt-5.6-sol" }` → `["-c", "model=\"gpt-5.6-sol\""]`. Dotted
 *  keys are passed through as-is (`mcp_servers.foo`), so the caller decides
 *  how deep an override reaches. */
export function codexConfigArgs(overrides: Record<string, unknown>): string[] {
  const args: string[] = [];
  for (const [key, value] of Object.entries(overrides)) {
    if (value === undefined) continue;
    args.push("-c", `${key}=${tomlValue(value)}`);
  }
  return args;
}

interface Pending {
  resolve: (value: any) => void;
  reject: (error: Error) => void;
  timer: ReturnType<typeof setTimeout>;
}

/** Bun types stdin/stdout as unions until the spawn options are read as
 *  literals; we always pass "pipe", so narrow once here rather than at every
 *  use site. */
type PipedProcess = ReturnType<typeof Bun.spawn> & {
  stdin: { write(chunk: string): void; end(): void; flush?(): void };
  stdout: AsyncIterable<Uint8Array>;
  stderr: AsyncIterable<Uint8Array>;
};

export class CodexAppServerClient {
  private proc: PipedProcess;
  private nextId = 1;
  private pending = new Map<number, Pending>();
  private buffer = "";
  private stopped = false;
  private exitCode: number | null | undefined;
  private handlers: CodexRpcHandlers;

  private constructor(proc: PipedProcess, handlers: CodexRpcHandlers) {
    this.proc = proc;
    this.handlers = handlers;
    void this.pumpStdout();
    void this.pumpStderr();
    void this.watchExit();
  }

  static spawn(opts: CodexAppServerSpawnOptions): CodexAppServerClient {
    const proc = Bun.spawn(
      [opts.executable || codexBinary(), ...(opts.configArgs || []), "app-server"],
      {
        env: opts.env,
        ...(opts.cwd ? { cwd: opts.cwd } : {}),
        stdin: "pipe",
        stdout: "pipe",
        stderr: "pipe",
      }
    );
    return new CodexAppServerClient(proc as PipedProcess, opts.handlers);
  }

  get alive(): boolean {
    return !this.stopped && this.exitCode === undefined;
  }

  /** The handshake codex expects: `initialize` request, then the
   *  `initialized` notification (same order codex-usage.ts uses). */
  async initialize(clientVersion = "1.0.0"): Promise<any> {
    const result = await this.request("initialize", {
      clientInfo: { name: "opensession", title: "Open Session", version: clientVersion },
    });
    this.notify("initialized", {});
    return result;
  }

  notify(method: string, params: unknown): void {
    this.write({ method, params });
  }

  request<T = any>(
    method: string,
    params: unknown,
    timeoutMs = DEFAULT_REQUEST_TIMEOUT_MS
  ): Promise<T> {
    if (!this.alive) {
      return Promise.reject(new Error(`codex app-server is not running (${method})`));
    }
    const id = this.nextId++;
    return new Promise<T>((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`codex app-server request "${method}" timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      this.pending.set(id, { resolve, reject, timer });
      try {
        this.write({ method, id, params });
      } catch (e: any) {
        this.pending.delete(id);
        clearTimeout(timer);
        reject(new Error(`codex app-server write failed: ${e?.message || e}`));
      }
    });
  }

  /** Terminate the child. Idempotent; pending requests reject. */
  kill(): void {
    if (this.stopped) return;
    this.stopped = true;
    try {
      this.proc.stdin.end();
    } catch {}
    try {
      this.proc.kill();
    } catch {}
    this.failPending("codex app-server was stopped");
  }

  private write(message: unknown): void {
    this.proc.stdin.write(`${JSON.stringify(message)}\n`);
    // Bun's FileSink buffers; a turn's control messages must not sit behind
    // the buffer while the child waits on stdin.
    try {
      this.proc.stdin.flush?.();
    } catch {}
  }

  private failPending(reason: string): void {
    const pending = [...this.pending.values()];
    this.pending.clear();
    for (const p of pending) {
      clearTimeout(p.timer);
      p.reject(new Error(reason));
    }
  }

  private async watchExit(): Promise<void> {
    try {
      const code = await this.proc.exited;
      this.exitCode = code;
      this.failPending(`codex app-server exited (code ${code})`);
      this.handlers.onExit?.(code);
    } catch {
      this.exitCode = null;
      this.failPending("codex app-server exited");
    }
  }

  private async pumpStderr(): Promise<void> {
    const stderr = this.proc.stderr;
    if (!stderr) return;
    const decoder = new TextDecoder();
    try {
      for await (const chunk of stderr) {
        this.handlers.onStderr?.(decoder.decode(chunk, { stream: true }));
      }
    } catch {
      // A closed stderr is not a failure of the run.
    }
  }

  private async pumpStdout(): Promise<void> {
    const decoder = new TextDecoder();
    try {
      for await (const chunk of this.proc.stdout) {
        this.buffer += decoder.decode(chunk, { stream: true });
        if (this.buffer.length > MAX_BUFFER_BYTES) {
          this.buffer = "";
          this.failPending("codex app-server sent an oversized message");
          this.kill();
          return;
        }
        let newline = this.buffer.indexOf("\n");
        while (newline >= 0) {
          const line = this.buffer.slice(0, newline).trim();
          this.buffer = this.buffer.slice(newline + 1);
          newline = this.buffer.indexOf("\n");
          if (line) this.handleLine(line);
        }
      }
    } catch (e: any) {
      this.failPending(`codex app-server read failed: ${e?.message || e}`);
    }
  }

  private handleLine(line: string): void {
    let message: any;
    try {
      message = JSON.parse(line);
    } catch {
      // Non-JSON on stdout is diagnostic noise from the binary, not a frame.
      this.handlers.onStderr?.(line);
      return;
    }
    if (!message || typeof message !== "object") return;

    // Response to one of our requests.
    if (message.id !== undefined && message.method === undefined) {
      const pending = this.pending.get(message.id);
      if (!pending) return;
      this.pending.delete(message.id);
      clearTimeout(pending.timer);
      if (message.error) {
        const err = new Error(message.error?.message || "codex app-server error");
        (err as { data?: unknown }).data = message.error?.data;
        (err as { code?: unknown }).code = message.error?.code;
        pending.reject(err);
      } else {
        pending.resolve(message.result);
      }
      return;
    }

    // Server→client request (has BOTH method and id): answer it.
    if (message.method && message.id !== undefined) {
      void this.answerRequest(message.id, String(message.method), message.params);
      return;
    }

    // Notification.
    if (message.method) {
      try {
        this.handlers.onNotification(String(message.method), message.params);
      } catch (e) {
        console.warn("[codex-direct] notification handler threw:", e);
      }
    }
  }

  private async answerRequest(id: unknown, method: string, params: any): Promise<void> {
    try {
      const result = await this.handlers.onRequest(method, params);
      this.write({ id, result: result ?? {} });
    } catch (e: any) {
      this.write({
        id,
        error: { code: -32000, message: e?.message || String(e) },
      });
    }
  }
}
