/**
 * codex-direct engine — OpenAI Codex as a first-party Open Session engine.
 *
 * Transport: the installed `codex` binary's app-server JSON-RPC surface, NOT
 * an SDK package. The reasoning is in codex-direct-protocol.ts's header; the
 * short version is that codex-usage.ts already runs this exact pattern in
 * production, the v2 protocol is a superset of any thin SDK wrapper (it has
 * `turn/steer`, `turn/interrupt`, typed `usageLimitExceeded`), and the schemas
 * are generated by the binary itself so a codex upgrade is checkable rather
 * than guessable.
 *
 * Containment / policy (the add-an-engine checklist):
 *  - Config gate, not an env flag: `directEngineEnabled("codex")`
 *    (engines-config.ts, `~/.opensession-engines.json`), read fresh per turn.
 *  - Kind gate copying `opencodeGateReason` semantics: deny by default on
 *    journal kind, kind-less runs refused, denials audited
 *    (`codex_direct_gate_denied`). The only escape is a module-scoped counter
 *    armed inside runCodexDirectSmokeTurn and matched to the private kind
 *    "codex-direct-smoke" — request/automation data can NAME that kind but
 *    can never arm the counter.
 *  - Auth: the shared codex-accounts pool via `pickOpenaiAccount` (same HRW
 *    affinity key convention as opencode, so a session keeps landing on the
 *    same account), seeded into an ISOLATED per-account CODEX_HOME —
 *    access-token-only with an invalid placeholder refresh, so this copy can
 *    never rotate the token family the live codex CLI logins depend on. See
 *    codex-direct-auth.ts. A usage-limit death calls `markCodexExhausted`
 *    (sideline state shared with opencode and pi) and flags
 *    `usageLimitExhausted` so agent-runner's fallback walk engages; a dry pool
 *    fails BEFORE any binary work, already flagged.
 *  - Tools: codex has no `canUseTool`, so enforcement is config-level.
 *    Ask mode gets a genuinely read-only sandbox (`readOnly`, no network) —
 *    stronger than a tool-name denylist, because it contains codex's built-in
 *    shell rather than removing it. Code mode gets `workspaceWrite` rooted at
 *    the session cwd. Denied and confirm tools are stripped from MCP servers
 *    through per-server `disabled_tools` (codex-direct-mcp.ts), and every
 *    sandbox-escape approval is screened: ask mode declines, unattended code
 *    mode runs the command through the org command policy
 *    (`bashAskPolicyReply`).
 *  - Subprocess env is minimal by construction (PATH/HOME/LANG/TERM + proxy
 *    and TLS passthrough + CODEX_HOME). No Open Session tokens. MCP servers
 *    receive their own credentials through the injected MCP config.
 *  - Journal: two-stage like the other in-process engines — a pre-engine
 *    record carrying the prompt, then an upgrade with the codex thread id in
 *    the journal's `claudeSessionId` slot (that field is the engine-session
 *    slot for every engine; the name is on-disk compat). NEVER a serverKey:
 *    the app-server child dies with the turn, so boot takes the continuation
 *    re-prompt path and `reattach` is null.
 *  - Transcript: store-only, the claude-direct recipe. `recordBksSessionFor`
 *    before any engine-keyed append; the user line is written early under the
 *    unified id with `opts.promptEntryId` as its uuid (so run-session's own
 *    early write upserts instead of duplicating), then re-appended keyed by
 *    the thread id. The codex rollout jsonl under the isolated CODEX_HOME is
 *    secondary evidence only — nothing reads it as the primary path.
 *  - Steer is REAL: `turn/steer` injects into the live turn, so steer()
 *    returns true while a turn id is live and false the moment it settles
 *    (callers then queue). The transcript user line for a steer is written at
 *    DELIVERY (codex's own userMessage item), never optimistically.
 *  - Exactly ONE terminal done/error per turn. A user cancel ends QUIETLY —
 *    the generator returns with no terminal event, so run-session records no
 *    failure for a run a human deliberately stopped.
 *  - Audit family `codex_direct_turn` (in/out, first-call-wins closer with a
 *    cancelled/abandoned finally backstop) plus `codex_direct_gate_denied`,
 *    field names matching `pi_turn`. Never raw prompt or reply text —
 *    `summarizeText` only.
 *
 * Documented v0 gaps:
 *  - No dial-oracle tool. codex 0.144.5's app-server has no client-side
 *    dynamic-tool registration (the `initialize` capabilities carry none, and
 *    `item/tool/call` dynamic tools come from plugin/app config), so an oracle
 *    would need either a codex plugin or a small stdio MCP entry point outside
 *    this module. Delegation still works through the opensession-sessions
 *    worker tools when the caller passes them in `inProcessMcp`.
 *  - `seedTranscriptEntries` is ignored (the handoff rides the prompt), same
 *    as pi and claude-direct.
 *  - Prompt images are passed as data-URL image inputs; codex accepts an image
 *    URL, but this specific shape has not been verified against a live turn.
 *  - api_key accounts are wired (see codex-direct-auth.ts) but unverified —
 *    there is no api_key account in the pool to test against.
 */

import { mkdirSync } from "fs";
import { audit, summarizeText } from "../audit";
import { bashAskPolicyReply } from "../command-policy";
import { markCodexExhausted, type CodexAccount } from "../codex-accounts";
import { readOpencodeBridgeConfig } from "../opencode-config";
import { maskOpenaiAccount, pickOpenaiAccount } from "../opencode-openai-auth";
import {
  baseJournalKind,
  isUnattendedKind,
  opencodeRunPolicy,
  readLocalInstructions,
  INTERACTIVE_KINDS,
} from "../opencode-policy";
import {
  appendOpencodeTranscript,
  recordBksSessionFor,
  storeAppendUserLineEarly,
  transcriptLineForEntry,
  transcriptLineRunnerNotice,
  transcriptLineUser,
} from "../opencode-transcript";
import { buildRunInstructions } from "../run-instructions";
import {
  buildRunJournalRecord,
  journalClear,
  journalSet,
  registerActiveRunProbe,
} from "../run-journal";
import { isCodexUsageLimitError, STRIPE_CONFIRM_TOOLS } from "../runner-shared";
import { transcriptStore } from "../transcript-store";
import type { TranscriptEntry } from "../types";
import { directEngineEnabled } from "./engines-config";
import {
  CODEX_DIRECT_STATE_DIR,
  codexDirectEnv,
  seedCodexDirectHome,
} from "./codex-direct-auth";
import { buildCodexMcpConfig } from "./codex-direct-mcp";
import { CodexAppServerClient, codexConfigArgs } from "./codex-direct-protocol";
import type {
  ActiveRunRecord,
  EngineAdapter,
  EngineAskHandler,
  ImageInput,
  RunAgentOpts,
  StreamEvent,
  TurnUsage,
} from "./adapter-types";

export { CODEX_DIRECT_STATE_DIR } from "./codex-direct-auth";

const g = globalThis as any;

/** StreamEvent's provider tag. The union already has "codex" (the legacy
 *  runner's slot), and reusing it keeps every consumer that switches on
 *  provider working without a protocol change. */
const PROVIDER = "codex" as const;

export const CODEX_DIRECT_MODEL_PREFIX = "codex/";

/** The private journal kind the smoke harness runs under. */
export const CODEX_DIRECT_SMOKE_KIND = "codex-direct-smoke";

/** The model the smoke turn runs on: known-good on the ChatGPT backend and
 *  present in every pool account's catalog. Reliability beats cost for a
 *  one-word probe. */
const SMOKE_MODEL = "gpt-5.6-sol";

// ── Config gate ──────────────────────────────────────────────────────────────

/** Whether the codex-direct engine may run at all. Config file, read fresh
 *  per call, so flipping it needs no restart. */
export function codexDirectEnabled(): boolean {
  return directEngineEnabled("codex");
}

// ── Kind gate ────────────────────────────────────────────────────────────────

/** Armed ONLY inside runCodexDirectSmokeTurn. Module-scoped and never
 *  exported: request/automation data can name the smoke kind but can never
 *  arm the counter. */
let smokeGateBypass = 0;

/** Non-null = the reason this run may not use the codex-direct engine.
 *  Same three-line body as opencodeGateReason / piGateReason. */
export function codexDirectGateReason(opts: { journal?: { kind?: string } }): string | null {
  const base = baseJournalKind(opts.journal?.kind);
  if (smokeGateBypass > 0 && base === CODEX_DIRECT_SMOKE_KIND) return null;
  if (INTERACTIVE_KINDS.has(base) || isUnattendedKind(base)) return null;
  return base
    ? `The codex-direct engine is not available to "${base}" runs — interactive sessions and automations only.`
    : "The codex-direct engine requires an explicit run kind (journal.kind) — " +
        "deny by default; interactive sessions and automations only.";
}

// ── Model ids ────────────────────────────────────────────────────────────────

/**
 * Normalize any id that should reach codex onto the bare model slug codex
 * itself understands. Accepts `codex/openai/<model>`, `codex/<model>`,
 * `opencode/openai/<model>`, `openai/<model>` and a bare `gpt-*`/`o*`/
 * `codex-*` id. Returns null for anything that is not an OpenAI model, so a
 * misrouted Anthropic id fails loudly instead of being handed to codex.
 */
export function parseCodexDirectModel(model: string): string | null {
  if (!model) return null;
  let id = model.trim();
  id = id.replace(/^codex\//i, "").replace(/^opencode\//i, "").replace(/^pi\//i, "");
  id = id.replace(/^openai\//i, "");
  if (!id || id.includes("/")) return null;
  return /^(gpt-|o[0-9]|codex-)/i.test(id) ? id : null;
}

/**
 * Open Session's effort scale → codex reasoning effort. "none" maps to
 * codex's "minimal" and "max" to "xhigh" (codex has no rung above it); an
 * effort codex already spells is passed through.
 */
export function codexReasoningEffort(effort?: string): string | undefined {
  if (!effort) return undefined;
  switch (effort) {
    case "none":
      return "minimal";
    case "low":
    case "medium":
    case "high":
    case "xhigh":
      return effort;
    case "max":
      return "xhigh";
    default:
      return effort;
  }
}

// ── Live-run registry ────────────────────────────────────────────────────────

interface CodexRunHandle {
  /** Hard cancel. Sets the quiet-cancel flag before interrupting. */
  cancel: () => void;
  /** Set while a turn id is live; cleared the instant the turn settles. */
  steer?: (text: string, images?: ImageInput[]) => boolean;
  cancelled: boolean;
}

/** Alias keys (run key, unified session id, transcript session id, codex
 *  thread id) → one shared handle. Parked on globalThis so a hot reload keeps
 *  cancel/steer working for in-flight turns. */
const activeRuns: Map<string, CodexRunHandle> = (g.__codexDirectActiveRuns ??= new Map());

if (!g.__codexDirectProbeRegistered) {
  g.__codexDirectProbeRegistered = true;
  registerActiveRunProbe((runKey) => activeRuns.has(runKey));
}

export function isCodexDirectBusy(id: string): boolean {
  return activeRuns.has(id);
}

export function activeCodexDirectRunCount(): number {
  return new Set(activeRuns.values()).size;
}

/** Nothing detaches: the app-server child dies with the turn. */
export function activeDetachedCodexDirectRunCount(): number {
  return 0;
}

export function cancelCodexDirectRun(id: string): boolean {
  const handle = activeRuns.get(id);
  if (!handle) return false;
  handle.cancel();
  return true;
}

export function steerCodexDirectRun(
  id: string,
  text: string,
  images?: ImageInput[]
): boolean {
  const handle = activeRuns.get(id);
  if (!handle?.steer) return false;
  return handle.steer(text, images);
}

// ── Transcript ───────────────────────────────────────────────────────────────

/** Store one batch of normalized entries keyed by the codex thread id. The
 *  thread→unified mapping must already be registered (recordBksSessionFor);
 *  unmapped batches are dropped by the store layer with a degraded mark.
 *  Best-effort — a transcript write must never take a run down. */
function persistEntries(threadId: string | undefined, entries: TranscriptEntry[]): void {
  if (!threadId || !entries.length) return;
  try {
    const lines = entries
      .map((e) =>
        e.type === "system"
          ? transcriptLineRunnerNotice(e.content, e.id, e.timestamp)
          : transcriptLineForEntry(e)
      )
      .filter((l): l is Record<string, unknown> => !!l);
    if (lines.length) appendOpencodeTranscript(threadId, lines);
  } catch (e) {
    console.warn("[codex-direct] transcript persist failed:", e);
  }
}

function nowIso(): string {
  return new Date().toISOString();
}

// ── Usage ────────────────────────────────────────────────────────────────────

interface TokenBreakdown {
  inputTokens?: number;
  cachedInputTokens?: number;
  outputTokens?: number;
  reasoningOutputTokens?: number;
  totalTokens?: number;
}

/** Fold one request's usage into the turn accumulator.
 *
 *  codex reports `total` cumulatively for the whole THREAD, which would
 *  over-count across turns of a resumed session, so the turn's figure is the
 *  sum of each request's `last` — literally "summed across all requests in
 *  the turn". `contextTokens` is the latest request's full prompt, which is
 *  the live "how full is the window" number consumers want.
 *
 *  codex counts cached input INSIDE `inputTokens`, so the split subtracts. */
export function foldCodexUsage(acc: TurnUsage, last: TokenBreakdown | undefined): TurnUsage {
  if (!last) return acc;
  const input = Math.max(0, Number(last.inputTokens || 0));
  const cached = Math.max(0, Number(last.cachedInputTokens || 0));
  const fresh = Math.max(0, input - cached);
  return {
    inputTokens: acc.inputTokens + fresh,
    outputTokens: acc.outputTokens + Math.max(0, Number(last.outputTokens || 0)),
    cacheReadTokens: acc.cacheReadTokens + cached,
    // codex has no explicit cache-write meter.
    cacheCreationTokens: 0,
    contextTokens: input,
  };
}

function emptyUsage(): TurnUsage {
  return {
    inputTokens: 0,
    outputTokens: 0,
    cacheReadTokens: 0,
    cacheCreationTokens: 0,
    contextTokens: 0,
  };
}

// ── Errors ───────────────────────────────────────────────────────────────────

/** codex's typed error info is the reliable signal; the string classifier is
 *  the fallback for transport-level failures that never reach a TurnError. */
export function isCodexDirectUsageLimit(
  codexErrorInfo: unknown,
  message: string
): boolean {
  if (typeof codexErrorInfo === "string") {
    if (codexErrorInfo === "usageLimitExceeded" || codexErrorInfo === "sessionBudgetExceeded") {
      return true;
    }
    // A typed non-limit error must NOT fall through to the loose string
    // classifier — "rate limit" in a prose message would sideline a healthy
    // account for an hour.
    return false;
  }
  return isCodexUsageLimitError(message);
}

// ── The turn ─────────────────────────────────────────────────────────────────

export async function* runCodexDirect(
  opts: RunAgentOpts,
  model: string
): AsyncGenerator<StreamEvent> {
  const modelId = parseCodexDirectModel(model) || model;
  const fail = (content: string, extra: Partial<StreamEvent> = {}): StreamEvent => ({
    type: "error",
    content,
    provider: PROVIDER,
    model: modelId,
    ...extra,
  });

  if (!codexDirectEnabled()) {
    yield fail(
      "codex-direct engine is disabled. Enable it in ~/.opensession-engines.json " +
        '({"codex":{"enabled":true}}) or from the Engines settings.'
    );
    return;
  }
  if (!parseCodexDirectModel(model)) {
    yield fail(`codex-direct only runs OpenAI models (got "${model}")`);
    return;
  }

  const journal = opts.journal;
  const gate = codexDirectGateReason({ journal });
  if (gate) {
    audit({
      msg: "codex_direct_gate_denied",
      run_kind: journal?.kind,
      session_id: journal?.osSessionId,
      reason: gate,
    });
    yield fail(gate);
    return;
  }

  const unifiedSessionId = journal?.osSessionId || opts.transcriptSessionId;
  const runKey = opts.sessionId || journal?.osSessionId || crypto.randomUUID();
  if (activeRuns.has(runKey)) {
    yield fail("codex-direct: this session already has a turn in flight");
    return;
  }

  const mode = opts.mode || "code";
  const isAsk = mode === "ask";
  const cwd = opts.cwd;
  const requestId = crypto.randomUUID();
  const started = Date.now();
  const runKind = journal?.kind;
  const confirmTools = { ...STRIPE_CONFIRM_TOOLS, ...(opts.confirmTools || {}) };

  const auditBase = {
    msg: "codex_direct_turn",
    request_id: requestId,
    run_key: runKey,
    session: unifiedSessionId,
    run_kind: runKind,
    resume: opts.sessionId,
    model: modelId,
    mode,
  };
  let turnClosed = false;
  const endTurn = (fields: Record<string, unknown>) => {
    if (turnClosed) return;
    turnClosed = true;
    audit({ ...auditBase, direction: "out", duration_ms: Date.now() - started, ...fields });
  };

  // ── Account ───────────────────────────────────────────────────────────────
  let designated: string[] | undefined;
  try {
    designated = readOpencodeBridgeConfig()?.openaiAccounts;
  } catch {
    designated = undefined;
  }
  const pickOut: { reason?: string } = {};
  const picked = pickOpenaiAccount(
    modelId,
    designated,
    opts.accountAffinityKey || journal?.osSessionId || cwd,
    pickOut,
    opts.user,
    opts.accountId,
    opts.accountStrict
  );
  if ("error" in picked) {
    // Pool dry at pick time — the fallback walk's cue, and no binary work has
    // happened yet.
    audit({ ...auditBase, direction: "in", ...summarizeText(opts.prompt) });
    endTurn({ ok: false, error: picked.error, usage_limit: true });
    yield fail(`codex-direct: ${picked.error}`, { usageLimitExhausted: true });
    return;
  }
  const account: CodexAccount = picked;

  const auth = seedCodexDirectHome(account);
  if ("error" in auth) {
    audit({ ...auditBase, direction: "in", ...summarizeText(opts.prompt) });
    endTurn({ ok: false, error: auth.error, account: maskOpenaiAccount(account) });
    yield fail(`codex-direct: ${auth.error}`);
    return;
  }

  audit({
    ...auditBase,
    direction: "in",
    account: maskOpenaiAccount(account),
    pick_reason: pickOut.reason,
    auth: auth.mechanism,
    ...summarizeText(opts.prompt),
    ...(Object.keys(opts.deniedTools || {}).length
      ? { denied_tools: Object.keys(opts.deniedTools || {}).length }
      : {}),
  });

  // ── Registry + cancellation ───────────────────────────────────────────────
  const handle: CodexRunHandle = { cancelled: false, cancel: () => {} };
  const registered = new Set<string>();
  const register = (id: string | undefined) => {
    if (!id || registered.has(id)) return;
    registered.add(id);
    activeRuns.set(id, handle);
  };
  register(runKey);
  register(unifiedSessionId);
  register(opts.sessionId);

  let client: CodexAppServerClient | null = null;
  let threadId: string | undefined = opts.sessionId;
  let turnId: string | undefined;
  let terminal: StreamEvent | null = null;
  let settled = false;
  let sawInit = false;
  let usage = emptyUsage();
  const queue: StreamEvent[] = [];
  let waiter: (() => void) | null = null;
  const wake = () => {
    const w = waiter;
    waiter = null;
    w?.();
  };
  const push = (event: StreamEvent) => {
    queue.push(event);
    wake();
  };
  const settle = (event: StreamEvent | null) => {
    if (settled) return;
    settled = true;
    handle.steer = undefined;
    terminal = event;
    wake();
  };

  handle.cancel = () => {
    handle.cancelled = true;
    handle.steer = undefined;
    if (client && turnId && threadId) {
      // Best-effort: give codex the chance to stop cleanly. We do not wait —
      // a user cancel ends the turn now.
      void client.request("turn/interrupt", { threadId, turnId }, 5_000).catch(() => {});
    }
    settle(null);
  };

  /** Engine-keyed appends are meaningless without a unified session to map
   *  them onto (recordBksSessionFor never ran), so skip them entirely rather
   *  than let the store drop them and mark the session degraded. */
  const persist = (entries: TranscriptEntry[]) => {
    if (!unifiedSessionId) return;
    persistEntries(threadId, entries);
  };

  const pendingSteers: string[] = [];
  let firstUserMessageSeen = false;
  /** Run-local: a module-scoped one would be clobbered by a concurrent run. */
  let cleanupRpc: (() => Promise<void>) | undefined;

  try {
    // ── Journal stage 1 + early user line ───────────────────────────────────
    const userLine = transcriptLineUser(opts.prompt, opts.promptEntryId, undefined, opts.images);
    if (journal?.osSessionId) {
      journalSet(
        buildRunJournalRecord(opts, {
          runKey,
          osSessionId: journal.osSessionId,
          claudeSessionId: opts.sessionId || undefined,
          prompt: opts.prompt,
          promptEntryId: String(userLine.uuid),
          cwd,
          mode,
          mcpServers: opts.mcpServers,
          user: opts.user,
          confirmTools: opts.confirmTools,
          model,
          effort: opts.effort,
          fastMode: opts.fastMode,
          accountId: account.id,
          accountStrict: opts.accountStrict,
          usageCredits: opts.usageCredits,
          kind: journal.kind,
        })
      );
    }
    if (unifiedSessionId) storeAppendUserLineEarly(unifiedSessionId, userLine, opts.sessionId);

    // ── Policy + MCP ────────────────────────────────────────────────────────
    const policy = opencodeRunPolicy({
      deniedTools: opts.deniedTools,
      confirmTools,
      journalKind: runKind,
      disableLocalWorkspaceTools: opts.disableLocalWorkspaceTools,
    });
    // Command-policy gate is kind-based (the trusted human loops carry
    // deniedTools but must not trip it), matching opencode and pi.
    const bashGated = isUnattendedKind(baseJournalKind(runKind)) && !isAsk;

    const rpcToken = opts.inProcessMcp && Object.keys(opts.inProcessMcp).length
      ? crypto.randomUUID()
      : undefined;
    if (rpcToken && unifiedSessionId) {
      const { registerRunToken, unregisterRunToken } = await import("../run-rpc");
      registerRunToken(rpcToken, { sessionId: unifiedSessionId, user: opts.user });
      // Deregistration rides the finally below via this closure.
      cleanupRpc = async () => unregisterRunToken(rpcToken);
    }

    const mcp = buildCodexMcpConfig({
      scope: opts.mcpServers,
      user: opts.user,
      grantUsers: [opts.mcpGrantUser, opts.user],
      deniedToolNames: [...Object.keys(opts.deniedTools || {}), ...Object.keys(confirmTools)],
      inProcessMcp: opts.inProcessMcp,
      rpcToken,
    });

    const instructions = buildRunInstructions({
      isAsk,
      isScratch: mode === "scratch",
      reposNote: opts.reposNote,
      prReviewer: opts.prReviewer,
      inProcessMcp: opts.inProcessMcp,
      osSessionId: unifiedSessionId,
      user: opts.user,
      author: opts.author,
      localInstructions: readLocalInstructions(cwd),
      deniedToolNotes: policy.noteGroups,
      commandPolicyGated: bashGated,
    });

    // ── Spawn ───────────────────────────────────────────────────────────────
    const configOverrides: Record<string, unknown> = {
      model: modelId,
      // The child's env is already minimal; be explicit so a future env change
      // can't widen what the model's shell inherits.
      "shell_environment_policy.inherit": "core",
      // Our workspace is trusted by construction (we chose the cwd); without
      // this codex prompts for trust on first use in a directory.
      [`projects.${JSON.stringify(cwd)}.trust_level`]: "trusted",
    };
    const effort = codexReasoningEffort(opts.effort);
    if (effort) configOverrides.model_reasoning_effort = effort;
    for (const [name, entry] of Object.entries(mcp.servers)) {
      configOverrides[`mcp_servers.${JSON.stringify(name)}`] = entry;
    }

    const env = codexDirectEnv(auth.codexHome, { ...auth.extraEnv, ...mcp.env });

    const stderrLines: string[] = [];
    client = CodexAppServerClient.spawn({
      env,
      cwd,
      configArgs: codexConfigArgs(configOverrides),
      handlers: {
        onNotification: (method, params) => onNotification(method, params),
        onRequest: (method, params) => onServerRequest(method, params),
        onStderr: (text) => {
          stderrLines.push(text);
          if (stderrLines.length > 200) stderrLines.splice(0, stderrLines.length - 200);
        },
        onExit: (code) => {
          if (settled || handle.cancelled) return;
          const detail = stderrLines.join("").trim().slice(-2_000);
          settle(
            fail(
              `codex-direct: the codex app-server exited (code ${code})${detail ? ` — ${detail}` : ""}`
            )
          );
        },
      },
    });

    // ── Notification → StreamEvent ──────────────────────────────────────────
    const deltaSeen = new Set<string>();

    function toolUseFor(item: any): StreamEvent | null {
      const id = String(item?.id || crypto.randomUUID());
      switch (item?.type) {
        case "commandExecution":
          return {
            type: "tool_use",
            toolName: "shell",
            toolInput: { command: item.command, cwd: item.cwd },
            toolUseId: id,
          };
        case "fileChange":
          return {
            type: "tool_use",
            toolName: "apply_patch",
            toolInput: { changes: item.changes },
            toolUseId: id,
          };
        case "mcpToolCall":
          return {
            type: "tool_use",
            toolName: `mcp__${item.server}__${item.tool}`,
            toolInput: item.arguments ?? {},
            toolUseId: id,
          };
        case "webSearch":
          return {
            type: "tool_use",
            toolName: "web_search",
            toolInput: { query: item.query },
            toolUseId: id,
          };
        default:
          return null;
      }
    }

    function toolResultText(item: any): { text: string; isError: boolean } | null {
      switch (item?.type) {
        case "commandExecution":
          return {
            text: String(item.aggregatedOutput ?? ""),
            isError: item.status === "failed" || item.status === "declined",
          };
        case "fileChange":
          return {
            text: `${item.status}: ${Object.keys(item.changes || {}).length} file(s) changed`,
            isError: item.status === "failed" || item.status === "declined",
          };
        case "mcpToolCall":
          return {
            text: item.error?.message
              ? String(item.error.message)
              : JSON.stringify(item.result ?? {}).slice(0, 100_000),
            isError: item.status === "failed" || !!item.error,
          };
        case "webSearch":
          return { text: String(item.query ?? ""), isError: false };
        default:
          return null;
      }
    }

    function onNotification(method: string, params: any): void {
      try {
        switch (method) {
          case "thread/started": {
            const id = params?.thread?.id;
            if (id) bindThread(String(id));
            return;
          }
          case "turn/started": {
            turnId = params?.turn?.id ? String(params.turn.id) : turnId;
            if (turnId && !settled) armSteer();
            return;
          }
          case "item/agentMessage/delta": {
            const itemId = String(params?.itemId || "");
            if (itemId) deltaSeen.add(itemId);
            const delta = String(params?.delta || "");
            if (delta) push({ type: "text_chunk", text: delta });
            return;
          }
          case "item/started": {
            const event = toolUseFor(params?.item);
            if (event) {
              push(event);
              persist([
                {
                  id: String(event.toolUseId),
                  type: "tool_use",
                  content: "",
                  timestamp: nowIso(),
                  toolName: event.toolName,
                  toolInput: event.toolInput,
                  toolUseId: event.toolUseId,
                },
              ]);
            }
            return;
          }
          case "item/completed": {
            const item = params?.item;
            if (!item) return;
            if (item.type === "agentMessage") {
              const text = String(item.text || "");
              if (text && !deltaSeen.has(String(item.id))) push({ type: "text_chunk", text });
              if (text) {
                persist([
                  {
                    id: String(item.id || crypto.randomUUID()),
                    type: "assistant",
                    content: text,
                    timestamp: nowIso(),
                    model: modelId,
                  },
                ]);
              }
              return;
            }
            if (item.type === "userMessage") {
              onUserMessageItem(item);
              return;
            }
            const result = toolResultText(item);
            if (result) {
              const id = String(item.id || crypto.randomUUID());
              push({
                type: "tool_result",
                toolUseId: id,
                result: result.text,
                content: result.text,
              });
              persist([
                {
                  id: `${id}-result`,
                  type: "tool_result",
                  content: result.text,
                  timestamp: nowIso(),
                  toolUseId: id,
                  ...(result.isError ? { isError: true } : {}),
                },
              ]);
            }
            return;
          }
          case "thread/tokenUsage/updated": {
            usage = foldCodexUsage(usage, params?.tokenUsage?.last);
            push({ type: "usage_snapshot", usage: { ...usage } });
            return;
          }
          case "error": {
            const message = String(params?.error?.message || "codex reported an error");
            if (params?.willRetry) {
              push({ type: "runner_notice", text: `codex is retrying after an error: ${message}` });
              return;
            }
            settleFromError(params?.error);
            return;
          }
          case "turn/completed": {
            const turn = params?.turn;
            if (turn?.status === "failed" || turn?.error) {
              settleFromError(turn?.error);
              return;
            }
            if (turn?.status === "interrupted") {
              // An interrupt we did not initiate still ends the turn; a user
              // cancel already set `cancelled` and settled quietly.
              settle(handle.cancelled ? null : fail("codex-direct: the turn was interrupted"));
              return;
            }
            settle({
              type: "done",
              sessionId: threadId,
              provider: PROVIDER,
              model: modelId,
              usage: { ...usage },
            });
            return;
          }
          default:
            return;
        }
      } catch (e) {
        console.warn(`[codex-direct] failed to handle ${method}:`, e);
      }
    }

    function settleFromError(error: any): void {
      const message = String(error?.message || "codex-direct: the turn failed");
      const detail = error?.additionalDetails ? ` (${error.additionalDetails})` : "";
      const usageLimit = isCodexDirectUsageLimit(error?.codexErrorInfo, message);
      if (usageLimit) markCodexExhausted(account.id, modelId);
      settle(
        fail(`codex-direct: ${message}${detail}`, usageLimit ? { usageLimitExhausted: true } : {})
      );
    }

    function onUserMessageItem(item: any): void {
      // codex echoes the turn's opening prompt as a userMessage item too;
      // only the ones after it can be delivered steers.
      if (!firstUserMessageSeen) {
        firstUserMessageSeen = true;
        return;
      }
      const text = Array.isArray(item?.content)
        ? item.content
            .filter((c: any) => c?.type === "text")
            .map((c: any) => String(c.text || ""))
            .join("")
        : "";
      if (!text) return;
      const idx = pendingSteers.indexOf(text);
      if (idx >= 0) pendingSteers.splice(idx, 1);
      // Delivery is when the steer becomes real, so this is where its
      // transcript line is written — never optimistically at accept time.
      persist([
        {
          id: String(item.id || crypto.randomUUID()),
          type: "user",
          content: text,
          timestamp: nowIso(),
        },
      ]);
      audit({ ...auditBase, kind: "steer_injected", ...summarizeText(text) });
    }

    function bindThread(id: string): void {
      if (!id || threadId === id) return;
      threadId = id;
      register(id);
      // W1 import-first gate: the thread→unified mapping must exist BEFORE
      // any engine-keyed append, or the store never sees the run.
      if (unifiedSessionId) recordBksSessionFor(id, unifiedSessionId);
      if (journal?.osSessionId) {
        journalSet(
          buildRunJournalRecord(opts, {
            runKey,
            osSessionId: journal.osSessionId,
            claudeSessionId: id,
            prompt: opts.prompt,
            promptEntryId: String(userLine.uuid),
            cwd,
            mode,
            mcpServers: opts.mcpServers,
            user: opts.user,
            confirmTools: opts.confirmTools,
            model,
            effort: opts.effort,
            fastMode: opts.fastMode,
            accountId: account.id,
            accountStrict: opts.accountStrict,
            usageCredits: opts.usageCredits,
            kind: journal.kind,
          })
        );
      }
      // Same uuid as the early write, so the store upserts one bubble.
      if (unifiedSessionId) {
        try {
          appendOpencodeTranscript(id, [userLine]);
        } catch (e) {
          console.warn("[codex-direct] user-line append failed:", e);
        }
      }
    }

    function armSteer(): void {
      handle.steer = (text: string, images?: ImageInput[]) => {
        if (settled || !client || !threadId || !turnId) return false;
        pendingSteers.push(text);
        audit({ ...auditBase, kind: "steer_queued", ...summarizeText(text) });
        void client
          .request("turn/steer", {
            threadId,
            expectedTurnId: turnId,
            input: userInputFor(text, images),
          })
          .catch((e) => {
            const idx = pendingSteers.indexOf(text);
            if (idx >= 0) pendingSteers.splice(idx, 1);
            audit({
              ...auditBase,
              kind: "steer_failed",
              error: String((e as Error)?.message || e),
            });
            push({
              type: "runner_notice",
              text: `A steer could not be delivered to codex: ${String((e as Error)?.message || e)}`,
            });
          });
        return true;
      };
    }

    // ── Server→client requests (approvals, asks) ────────────────────────────
    async function onServerRequest(method: string, params: any): Promise<unknown> {
      switch (method) {
        case "item/commandExecution/requestApproval":
        case "execCommandApproval": {
          const legacy = method === "execCommandApproval";
          const command = String(params?.command || "");
          const decision = approveCommand(command);
          return legacy
            ? { decision: decision ? "approved" : "denied" }
            : { decision: decision ? "accept" : "decline" };
        }
        case "item/fileChange/requestApproval":
        case "applyPatchApproval": {
          const legacy = method === "applyPatchApproval";
          const allow = !isAsk;
          return legacy
            ? { decision: allow ? "approved" : "denied" }
            : { decision: allow ? "accept" : "decline" };
        }
        case "item/permissions/requestApproval":
          // Grant nothing: a run's reach is the sandbox policy it started
          // with, not something the model can widen mid-turn.
          return { permissions: {} };
        case "mcpServer/elicitation/request":
          return { action: "decline" };
        case "item/tool/requestUserInput":
          return await answerUserInput(params);
        case "account/chatgptAuthTokens/refresh":
          // The isolated CODEX_HOME is a deliberately non-refreshable copy —
          // see codex-direct-auth.ts. Fail loudly rather than let anything
          // rotate the shared token family.
          throw new Error(
            "codex-direct never refreshes tokens: run a codex turn on the account's own " +
              "CODEX_HOME to refresh it, then retry"
          );
        default:
          throw new Error(`codex-direct does not support the "${method}" request`);
      }
    }

    function approveCommand(command: string): boolean {
      // Ask mode runs read-only: an approval request IS the escalation, so it
      // is refused rather than turned into a write.
      if (isAsk) return false;
      if (bashGated) {
        const reply = bashAskPolicyReply(
          { permission: "bash", metadata: { command } },
          { unattended: true, gated: true, sessionId: unifiedSessionId, runKind }
        );
        if (reply === "reject") return false;
      }
      return true;
    }

    async function answerUserInput(params: any): Promise<unknown> {
      const questions = Array.isArray(params?.questions) ? params.questions : [];
      const onAskUser: EngineAskHandler | undefined = opts.onAskUser;
      if (!onAskUser) {
        return {
          answers: questions.map(() => ({
            answers: [
              "No interactive ask handler on this run — decide with your best judgment and continue.",
            ],
          })),
        };
      }
      const answers: Array<{ answers: string[] }> = [];
      for (const question of questions) {
        const decision = await onAskUser({ questions: [question] });
        if (decision.behavior === "deny") {
          answers.push({ answers: [decision.message] });
          continue;
        }
        const updated = decision.updatedInput as Record<string, unknown>;
        const answer =
          typeof updated?.answer === "string"
            ? updated.answer
            : JSON.stringify(updated ?? {});
        answers.push({ answers: [answer] });
      }
      return { answers };
    }

    function userInputFor(text: string, images?: ImageInput[]): unknown[] {
      const input: unknown[] = [{ type: "text", text }];
      for (const image of images || []) {
        input.push({ type: "image", url: `data:${image.mediaType};base64,${image.data}` });
      }
      return input;
    }

    // ── Handshake + thread ──────────────────────────────────────────────────
    await client.initialize();
    if (handle.cancelled) return;

    const threadParams = {
      cwd,
      model: modelId,
      developerInstructions: instructions,
      sandbox: isAsk ? "read-only" : "workspace-write",
    };
    if (opts.sessionId) {
      try {
        const resumed: any = await client.request("thread/resume", {
          ...threadParams,
          threadId: opts.sessionId,
        });
        bindThread(String(resumed?.thread?.id || opts.sessionId));
      } catch (e) {
        // A pruned/absent rollout must not silently start a blank session
        // pretending to be a resume — say so in the stream.
        push({
          type: "runner_notice",
          text:
            `codex could not resume thread ${opts.sessionId} ` +
            `(${String((e as Error)?.message || e)}); starting a fresh codex thread.`,
        });
        const startedThread: any = await client.request("thread/start", threadParams);
        bindThread(String(startedThread?.thread?.id || ""));
      }
    } else {
      const startedThread: any = await client.request("thread/start", threadParams);
      bindThread(String(startedThread?.thread?.id || ""));
    }
    if (handle.cancelled) return;
    if (!threadId) throw new Error("codex did not return a thread id");

    sawInit = true;
    yield { type: "init", sessionId: threadId, provider: PROVIDER, model: modelId };

    if (mcp.skipped.length) {
      const note =
        "Some MCP connectors are not available on this engine: " +
        mcp.skipped.map((s) => `${s.name} (${s.reason})`).join("; ");
      persist([
        { id: `cx-${requestId}-mcpskip`, type: "system", content: note, timestamp: nowIso() },
      ]);
      yield { type: "runner_notice", text: note };
    }
    if (mcp.unenforceable.length) {
      console.warn(
        `[codex-direct] ${mcp.unenforceable.length} denied tool name(s) cannot be expressed as ` +
          `codex disabled_tools: ${mcp.unenforceable.join(", ")}`
      );
    }

    // ── Turn ────────────────────────────────────────────────────────────────
    const turnParams: Record<string, unknown> = {
      threadId,
      input: userInputFor(opts.prompt, opts.images),
      model: modelId,
      cwd,
      approvalPolicy: "on-request",
      sandboxPolicy: isAsk
        ? { type: "readOnly", networkAccess: false }
        : {
            type: "workspaceWrite",
            writableRoots: [cwd],
            networkAccess: true,
          },
    };
    if (effort) turnParams.effort = effort;
    const startedTurn: any = await client.request("turn/start", turnParams);
    turnId = startedTurn?.turn?.id ? String(startedTurn.turn.id) : turnId;
    if (turnId && !settled) armSteer();

    // ── Pump ────────────────────────────────────────────────────────────────
    while (!settled || queue.length) {
      if (queue.length) {
        yield queue.shift()!;
        continue;
      }
      await new Promise<void>((resolve) => {
        waiter = resolve;
      });
    }

    if (handle.cancelled) {
      // A user cancel ends QUIETLY: no terminal event, so run-session records
      // no failure and no parent is pinged about a worker a human stopped.
      if (journal?.osSessionId) journalClear(runKey);
      endTurn({ ok: false, status: "cancelled", codex_thread_id: threadId });
      return;
    }

    const final: StreamEvent =
      terminal ?? fail("codex-direct: the turn ended without a result");
    endTurn({
      ok: final.type === "done",
      codex_thread_id: threadId,
      saw_init: sawInit,
      account: maskOpenaiAccount(account),
      ...(final.type === "done"
        ? {
            input_tokens: final.usage?.inputTokens,
            output_tokens: final.usage?.outputTokens,
            cache_read_input_tokens: final.usage?.cacheReadTokens,
          }
        : {
            error: final.content,
            ...(final.usageLimitExhausted ? { usage_limit: true } : {}),
          }),
    });
    if (journal?.osSessionId) journalClear(runKey);
    yield final;
  } catch (e: any) {
    const message: string = e?.message || String(e);
    if (handle.cancelled) {
      if (journal?.osSessionId) journalClear(runKey);
      endTurn({ ok: false, status: "cancelled" });
      return;
    }
    const usageLimit = e?.usageLimitExhausted === true;
    if (usageLimit) markCodexExhausted(account.id, modelId);
    endTurn({ ok: false, error: message, codex_thread_id: threadId });
    if (journal?.osSessionId) journalClear(runKey);
    yield fail(`codex-direct: ${message}`, usageLimit ? { usageLimitExhausted: true } : {});
  } finally {
    // A consumer teardown mid-turn keeps the journal record (nothing survives
    // to reattach, so boot re-prompts) but must still stop the child.
    endTurn({ ok: false, status: "abandoned", codex_thread_id: threadId });
    handle.steer = undefined;
    try {
      client?.kill();
    } catch {}
    for (const id of registered) {
      if (activeRuns.get(id) === handle) activeRuns.delete(id);
    }
    try {
      await cleanupRpc?.();
    } catch {}
  }
}

// ── Adapter object ───────────────────────────────────────────────────────────

export const codexDirectAdapter: EngineAdapter = {
  name: "codex-direct",
  startTurn: (opts: RunAgentOpts, model: string) => runCodexDirect(opts, model),
  steer: steerCodexDirectRun,
  cancel: cancelCodexDirectRun,
  isBusy: isCodexDirectBusy,
  // Nothing detaches: the app-server child dies with the turn, so boot always
  // takes the continuation re-prompt path.
  reattach: async (_run: ActiveRunRecord) => null,
  activeDetachedRunCount: activeDetachedCodexDirectRunCount,
};

// ── Scripted smoke harness ───────────────────────────────────────────────────

export interface CodexDirectSmokeOptions {
  prompt?: string;
  /** Wiring probe: never execute a turn even when the engine is enabled — no
   *  account pick, no binary spawn. */
  dryRun?: boolean;
  /** Wall cap (default 120s, clamped 5s–10min). Expiry cancels through the
   *  normal path, which ends the turn quietly. */
  timeoutMs?: number;
  model?: string;
}

export interface CodexDirectSmokeResult {
  ok: boolean;
  enabled: boolean;
  dryRun: boolean;
  reason?: string;
  sessionId: string;
  engineSessionId?: string;
  model: string;
  eventTypes: string[];
  text: string;
  error?: string;
  usage?: TurnUsage;
  timedOut: boolean;
  durationMs: number;
  storeRows: number;
}

/**
 * One tiny scripted turn against a throwaway session id
 * (`os-test-codex-direct-*`), for post-restart verification. With the engine
 * DISABLED this is a pure dry run: runCodexDirect stops at its config gate
 * before touching accounts or the binary. Never throws, and a real turn is
 * hard-capped at `timeoutMs`.
 */
export async function runCodexDirectSmokeTurn(
  opts: CodexDirectSmokeOptions = {}
): Promise<CodexDirectSmokeResult> {
  const prompt = opts.prompt || "Reply with exactly the single word: ok";
  const timeoutMs = Math.max(5_000, Math.min(opts.timeoutMs ?? 120_000, 600_000));
  const model = opts.model || SMOKE_MODEL;
  const enabled = codexDirectEnabled();
  const sessionId = `os-test-codex-direct-${Date.now().toString(36)}`;
  const started = Date.now();
  const storeRowsFor = (id: string): number => {
    try {
      return transcriptStore().getLastSeq(id);
    } catch {
      return 0;
    }
  };

  if (enabled && opts.dryRun) {
    return {
      ok: true,
      enabled,
      dryRun: true,
      reason:
        "dry run requested — the engine is ON but no turn was executed (no account pick, no codex spawn)",
      sessionId,
      model,
      eventTypes: [],
      text: "",
      timedOut: false,
      durationMs: Date.now() - started,
      storeRows: 0,
    };
  }

  const cwd = `${CODEX_DIRECT_STATE_DIR}/smoke`;
  if (enabled) {
    try {
      mkdirSync(cwd, { recursive: true });
    } catch {}
  }

  const eventTypes: string[] = [];
  let text = "";
  let error: string | undefined;
  let usage: TurnUsage | undefined;
  let engineSessionId: string | undefined;
  let done = false;
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    cancelCodexDirectRun(sessionId);
  }, timeoutMs);

  smokeGateBypass++;
  try {
    for await (const event of runCodexDirect(
      {
        prompt,
        cwd,
        mode: "ask",
        mcpServers: [],
        journal: { osSessionId: sessionId, kind: CODEX_DIRECT_SMOKE_KIND },
      },
      model
    )) {
      eventTypes.push(event.type);
      if (event.type === "init") engineSessionId = event.sessionId;
      if (event.type === "text_chunk") text += event.text || "";
      if (event.type === "error") error = event.content;
      if (event.type === "done") {
        usage = event.usage;
        done = true;
      }
    }
  } catch (e) {
    error = String((e as Error)?.message || e);
  } finally {
    smokeGateBypass--;
    clearTimeout(timer);
  }

  return {
    ok: done && !timedOut && !error,
    enabled,
    dryRun: !enabled,
    reason: !enabled
      ? "codex-direct is disabled in ~/.opensession-engines.json — the gate error below is the " +
        "expected dry-run result; no account or codex use happened"
      : timedOut
        ? `smoke turn exceeded the ${timeoutMs}ms wall cap and was cancelled`
        : undefined,
    sessionId,
    engineSessionId,
    model,
    eventTypes,
    text,
    error,
    usage,
    timedOut,
    durationMs: Date.now() - started,
    storeRows: enabled ? storeRowsFor(sessionId) : 0,
  };
}
