import posterAsset from "./demo-poster.webp";
import posterDarkAsset from "./demo-poster-dark.webp";
import phoneAsset from "./demo-phone.webp";
import phoneDarkAsset from "./demo-phone-dark.webp";
import { assetUrl } from "./asset-url";

const posterUrl = assetUrl(posterAsset);
const posterDarkUrl = assetUrl(posterDarkAsset);
const phoneUrl = assetUrl(phoneAsset);
const phoneDarkUrl = assetUrl(phoneDarkAsset);

export function ProductDemo() {
	return (
		<>
			{/* This is deliberately a local moving-poster composition, not a live
			    Open Session client. It must paint on the first frame and must never
			    depend on the visitor's server, network, or stored product state. */}
			<figure className="preview-wrap">
				<picture>
					<source srcSet={posterDarkUrl} media="(prefers-color-scheme: dark)" />
					<img
						className="product-demo-poster"
						src={posterUrl}
						alt="The Open Session workspace: a list of sessions beside a transcript."
						fetchPriority="high"
					/>
				</picture>
			</figure>

			{/* The same deterministic composition on a phone. Both files are
			    regenerated by scripts/capture-demo-poster.ts when the product chrome
			    changes, but neither runs the product on the landing page. */}
			<picture>
				<source srcSet={phoneDarkUrl} media="(prefers-color-scheme: dark)" />
				<img
					className="demo-phone"
					src={phoneUrl}
					alt="The same session open in Open Session on a phone."
				/>
			</picture>
		</>
	);
}
